import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Contactsection from "@/components/Contactsection";
import { ThemeProvider } from "next-themes"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My portfolio",
  description: "Generated by create next app",
};

//children is what is coming from the page.js file
export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <ThemeProvider attribute="class">
          <Navbar />
          {children}
          <Contactsection />
        </ThemeProvider>
      </body>

    </html>
  );
}
